name: Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  go-lint:
    name: Go Lint
    uses: harryzcy/github-actions/.github/workflows/golangci-lint.yml@81aad314153d8b8fd8dc8cfa277e1a2f637992fa # main

  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@81aad314153d8b8fd8dc8cfa277e1a2f637992fa # main

  spelling:
    name: Spelling
    uses: harryzcy/github-actions/.github/workflows/spelling.yml@81aad314153d8b8fd8dc8cfa277e1a2f637992fa # main
