name: Releases

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    name: Release on GitHub
    permissions:
      contents: write
    uses: harryzcy/github-actions/.github/workflows/release.yml@main
