name: Releases

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    name: Release on GitHub
    permissions:
      contents: write
    uses: harryzcy/github-actions/.github/workflows/release.yml@4b1a8cebf62d55102a11b7823db49d0dcc82fa51 # main
