name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  go-test:
    name: Go Unit Tests
    permissions:
      id-token: write
      contents: read
    uses: harryzcy/github-actions/.github/workflows/go.yml@88f6d74880d1878315508426dde7a8aaf6cb3d88 # main
    with:
      latest: 1
