name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  go-test:
    name: Go Unit Tests
    permissions:
      id-token: write
      contents: read
    uses: harryzcy/github-actions/.github/workflows/go.yml@2b18cd8e46647c70be37720c3d268811b62b8045 # main
    with:
      latest: 1
