name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  go-test:
    name: Go Unit Tests
    permissions:
      id-token: write
      contents: read
    uses: harryzcy/github-actions/.github/workflows/go.yml@87c34ce6929775ac6d5f18b0eefb70c098151418 # main
    with:
      latest: 1
