name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  go-test:
    name: Go Unit Tests
    uses: harryzcy/github-actions/.github/workflows/go.yml@main
